# Generated by Django 4.1 on 2022-11-06 21:25

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
         ('django_ltree', '__latest__'),
    ]