# Generated by Django 4.2.7 on 2023-12-03 23:00

import accounts.models
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="The users cognito username",
                        max_length=36,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="Users first name", max_length=100),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Users last name", max_length=100),
                ),
                (
                    "full_name",
                    models.CharField(
                        editable=False,
                        help_text="Users full name (diacritics removed and populated automatially)",
                        max_length=201,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Hi", max_length=254, null=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Users phone number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "professional_title",
                    models.CharField(
                        blank=True,
                        help_text="The users professional title",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            managers=[
                ("objects", accounts.models.ExtendedUserManager()),
            ],
        ),
    ]
