# Generated by Django 4.2.1 on 2023-06-06 16:40

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models

import django_extras.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    django_extras.fields.LTreeField(
                        default=None,
                        editable=False,
                        help_text="Path used for the ltree on %(class)",
                        null=True,
                    ),
                ),
                ("field1", models.CharField(blank=True, default="", max_length=100)),
                ("field2", models.CharField(blank=True, default="", max_length=100)),
                (
                    "protected_field",
                    models.CharField(default="", max_length=100, null=True),
                ),
                (
                    "choice_field",
                    django_extras.fields.SetChoiceField(default=set, null=True),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        help_text="The parent %(class)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_parent",
                        to="django_extras.testmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    django.contrib.postgres.indexes.BTreeIndex(
                        fields=["path"], name="django_extr_path_782341_btree"
                    ),
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["path"], name="django_extr_path_e406b7_gist"
                    ),
                ],
            },
        ),
    ]
