from clients.config.models import (
    FILTERSET_CLIENT_USER_PERMISSION_LIST,
    MODEL_CLIENT,
    MODEL_MIXIN_CLIENT_GATING_USER,
    PERMISSIONS_CLIENT_GATING_MIXIN,
    SERIALIZER_MIXIN_CLIENT_GATING_USER,
)
from core.config.models import MODEL_TAG
from tasks.config.models import MODEL_ASSIGNEE, MODEL_STAGE, MODEL_TASK

# Required foreign models
MODEL_ASSIGNEE = MODEL_ASSIGNEE
MODEL_STAGE = MODEL_STAGE
MODEL_TASK = MODEL_TASK
MODEL_CLIENT = MODEL_CLIENT
MODEL_MIXIN_CLIENT_GATING_USER = MODEL_MIXIN_CLIENT_GATING_USER

# Required foreign serializers
SERIALIZER_MIXIN_CLIENT_GATING_USER = SERIALIZER_MIXIN_CLIENT_GATING_USER
MODEL_TAG = MODEL_TAG

# Required foreign filtersets
FILTERSET_CLIENT_USER_PERMISSION_LIST = FILTERSET_CLIENT_USER_PERMISSION_LIST
# Required foreign Business
PERMISSIONS_CLIENT_GATING_MIXIN = PERMISSIONS_CLIENT_GATING_MIXIN
